#!/bin/bash 

if [ -z $TOKEN ] 
	then
	if [ -z token ]; then 
		echo 'No token; please export TOKEN=<token>'; 
		exit -1; 
	else
		TOKEN=$(<token);
	fi
fi

curl -s  -H "Authorization: Bearer $TOKEN" https://api.digitalocean.com/v2/droplets/$1/backups | jq '.backups[] | {id: .id, name: .name, created: .created_at } '
